/*

getSpendingReport method not recognizing Strings "month" and "year":
    move method to LayoutSpendingReport and change spendingReport list adapter accordingly
        have list appear only on "show report" button being pushed

FORMULA FOR SAVINGS DATE CALCULATION
DBL CHECK CALCULATION FOR DEBT DATE
WARNING WHEN WEEKLY LIMIT ALREADY SPENT
CHANGE MENU (ADD SPENDING REPORT)
ADD SPENDING REPORT (USER CAN CHOOSE FILTERS FOR REPORT)
ADD GENERATE BUDGET FUNCTION
RED EXCLAMATION MARKS TO SHOW UP ON TABS OR MENU TO FLAG ISSUES
ADD RATINGS REQUEST
DBL CHECK ONBOARDING GOOD
BUILD HELP SECTIONS
HANDLE ZEROS & EMPTY FIELDS
MAKE SURE STRINGS ARE STRING RESOURCES
ADD CONTENT DESCRIPTIONS
TRANSLATE STRINGS TO FRENCH
CHECK WHAT HAPPENS IF YOU GO TO THE HELP SECTION BEFORE BEING DONE THE ONBOARDING AND TRY TO RETURN TO THE ONBOARDING STEPS

FORMATTING:
ADD BOXES FOR DATA ENTRY IN MONEY IN, MONEY OUT, & MONEY CC SCREENS
CHANGE TEXT TO RED WHEN OVER SPENT IN WEEKLY LIMITS

*/