/*

ADD DIALOG BOX TO LAYOUTCCPAY

ADD COMPONENT TO FINANCIAL SUMMARY THAT MAKES SURE BUDGETED B ITEMS DON'T GO OVER INCOME AMT

REDUCE SIZE OF BOX THAT LIMITS SIZE OF SELECTED LIST (WITH 2 SPINNERS IN IT)

ADD ABILITY TO PAY CC FROM OTHER ACCTS

DOUBLE CHECK FORMULA THAT MAKES NEW EXP ANN AMT AND NEW INC ANN AMT

DOUBLE CHECK EVERY FUNCTION FROM EVERY SCREEN

UPDATE HELP PAGES

FIX SHADOW OF SET UP THAT APPEARS FIRST WHEN FIRST OPENS MAIN SCREEN

CLEAN UP CODE

LASTPAGEID:
1 LAYOUTMONEYIN
2 LAYOUTBUDGET
3 LAYOUTMONEYOUT
4 LAYOUTWEEKLYLIMITSLIST
5 LAYOUTDEBT
6 LAYOUTSAVINGS
7 LAYOUTCCPUR
8 LAYOUTTRANSFERS
9 LAYOUTWEEKLYLIMITS
10
11 ADDDEBTS
12 LAYOUTDAILYMONEY
13 ADDSAVINGS

*/