/*

DO ONBOARDING FOR LANDSCAPE
BUILD HELP SECTIONS
ADD RATINGS REQUEST
HANDLE ZEROS & EMPTY FIELDS
MAKE SURE STRINGS ARE STRING RESOURCES
ADD CONTENT DESCRIPTIONS
TRANSLATE STRINGS TO FRENCH
CHECK WHAT HAPPENS IF YOU GO TO THE HELP SECTION BEFORE BEING DONE THE ONBOARDING AND TRY TO RETURN TO THE ONBOARDING STEPS

FORMATTING:
ADD BOXES FOR DATA ENTRY IN MONEY IN, MONEY OUT, & MONEY CC SCREENS
CHANGE TEXT TO RED WHEN OVER SPENT IN WEEKLY LIMITS

*/